---
- name: clone thing
  hosts: all
  become: true
  become_user: true

  tasks:
  - name: Clone a private repository into /opt.
    shell: cd /var/www/html & git clone https://github.com/VladimirMaljkovic/php1cas.git