---
- name: clone thing
  hosts: all
  become: true
  become_user: root

  tasks:
  - name: install python
    apt: name=python state=present

  - name: read write git checkout
    git:
      repo: https://github.com/VladimirMaljkovic/MavenBiblioteka.git
      version: master
      dest: /home/vladimir/MavenBiblioteka
      accept_hostkey: yes
    become: yes
    become_user: vladimir
