---
- name: clone thing
  hosts: all
  become: true
  become_user: root

  tasks:
  - name: read write git checkout
    ansible.builtin.git:
      repo: 'https://github.com/VladimirMaljkovic/php1cas'
      dest: /home/vladimir/php1cas
