---
- name: clone thing
  hosts: all

  tasks:
  - name: Clone a private repository into /opt.
    git:
      repo: https://github.com/VladimirMaljkovic/php1cas
      version: master
      dest: /var/www/html
      accept_hostkey: yes