---
- name: clone thing
  hosts: all
  become: true
  become_user: root

  tasks:
  - name: install python
    apt: name=python state=present

  - name: read write git checkout
    git:
      repo: git@github.com:VladimirMaljkovic/php1cas.git'
      version: master
      dest: /home/vladimir/php1cas
      accept_hostkey: yes
