---
- name: clone thing
  hosts: all
  become: true
  become_user: true

  tasks:
  - name: Clone a private repository into /opt.
    git:
      repo: https://github.com/VladimirMaljkovic/php1cas
      version: master
      dest: /var/www/html/php1cas
      accept_hostkey: yes